name: Update

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set name in local git-config
      run: git config --local user.name "runner"
    - uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: swift update.swift ${{ secrets.GITHUB_TOKEN }}
