name: Update

on:
  schedule:
    - cron:  '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2
    - name: Set Xcode 13.2
      run: sudo xcode-select --switch /Applications/Xcode_13.2.app/Contents/Developer
    - name: Run update script
      run: swift update.swift ${{ secrets.GITHUB_TOKEN }}
