name: Update

on:
  schedule:
    - cron:  '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run update script
      run: swift update.swift ${{ secrets.GITHUB_TOKEN }}
