name: Update

on:
  schedule:
    - cron:  '0 0,6,12,18 * * *'
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

jobs:
  update:
    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2
    - name: Compile update script
      run: xcrun swiftc -parse-as-library update.swift
    - name: Run update script
      run: ./update ${{ secrets.GITHUB_TOKEN }}
